// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHTUI5tO7z2M2loHsIVwxqc-jG3S4pgzo',
    appId: '1:760828964815:web:03598428b517063b99ecba',
    messagingSenderId: '760828964815',
    projectId: 'tea-checker',
    authDomain: 'tea-checker.firebaseapp.com',
    storageBucket: 'tea-checker.firebasestorage.app',
    measurementId: 'G-GBP25PFH0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bMTh7XWj4DBBaLRY84hX-w_eZxhx5Z4',
    appId: '1:760828964815:android:da19a7c93933c62699ecba',
    messagingSenderId: '760828964815',
    projectId: 'tea-checker',
    storageBucket: 'tea-checker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECW_LDzA3EDKgU62SKFHEhV1zE7sSNUA',
    appId: '1:760828964815:ios:02c3f3b29f5a6a6799ecba',
    messagingSenderId: '760828964815',
    projectId: 'tea-checker',
    storageBucket: 'tea-checker.firebasestorage.app',
    iosBundleId: 'com.example.teaChecker',
  );
}
